### ISSUE TITLE
IT translation : Adobe -> Adobi

### ISSUE THREAD

**Issue by marcocucinato** [AdobeDocs/experience-manager-learn.it-IT#1]
Issue in ./help/assets/creative-workflows/adobe-express.md

When auto-traslated to Italian, "Adobe Express" becomes "Adobi Express".

**Comment by marcocucinato** [comment]
![image](https://github.com/AdobeDocs/experience-manager-learn.it-IT/assets/1677859/9ce3295f-6de0-48ec-83fc-ba0e5444126c)

**Comment by Roberta-A** [comment]
Thank you Marco
this page is currently auto-translated, it will be fixed in the actual localized page

**Comment by Roberta-A** [comment]
Thank you again for your feedback, Marco. This is being reviewed and tracked in G11N-14879

**Comment by Roberta-A** [comment]
This issue is now fixed, and the localized page is now live
